#!/bin/bash

# ===================================================================
# SPRING BOOT MICROSERVICES DOCKER DEPLOYMENT
# ===================================================================
# 
# This script provides CONTAINERIZED deployment using Docker Compose
# 
# Containerized deployment advantages:
# ✅ Isolated environments
# ✅ No local infrastructure setup required  
# ✅ Consistent across development machines
# ✅ Easy scaling and management
# ✅ Production-ready setup
# ✅ Automated database migrations
# ===================================================================

echo "🚀 Starting Spring Boot Microservices in Docker..."

# Build the microservices JARs first
echo "🔨 Building microservices..."
echo "📚 Building Book Service..."
cd book-service && mvn clean package -DskipTests
if [ $? -ne 0 ]; then
    echo "❌ Failed to build book-service"
    exit 1
fi
cd ..

echo "👥 Building User Service..."
cd user-service && mvn clean package -DskipTests  
if [ $? -ne 0 ]; then
    echo "❌ Failed to build user-service"
    exit 1
fi
cd ..

# Start infrastructure services first
echo "🏗️ Starting infrastructure services..."
docker-compose up -d mysql redis zookeeper kafka redis-commander kafka-ui

# Wait for infrastructure to be healthy
echo "⏳ Waiting for infrastructure services to be ready..."
sleep 30

# Check infrastructure health
echo "🔍 Checking infrastructure health..."
docker-compose ps

# Create Kafka topics
echo "📋 Creating Kafka topics..."
echo "  📚 Creating book-events topic..."
docker exec bookstore-kafka kafka-topics --bootstrap-server localhost:9092 --create --topic book-events --partitions 3 --replication-factor 1 --if-not-exists

echo "  📚 Creating book-cdc-events topic..."
docker exec bookstore-kafka kafka-topics --bootstrap-server localhost:9092 --create --topic book-cdc-events --partitions 3 --replication-factor 1 --if-not-exists

echo "  👥 Creating user-events topic..."
docker exec bookstore-kafka kafka-topics --bootstrap-server localhost:9092 --create --topic user-events --partitions 3 --replication-factor 1 --if-not-exists

echo "  👥 Creating user-cdc-events topic..."
docker exec bookstore-kafka kafka-topics --bootstrap-server localhost:9092 --create --topic user-cdc-events --partitions 3 --replication-factor 1 --if-not-exists

echo "✅ Kafka topics created successfully"

# List created topics
echo "📋 Listing Kafka topics:"
docker exec bookstore-kafka kafka-topics --bootstrap-server localhost:9092 --list

# Run database migrations (skipped since Liquibase is disabled)
echo "🗄️ Database migrations are handled by Hibernate DDL (Liquibase disabled)"
echo "✅ Database schema will be auto-generated by microservices"

# Build and start microservices
echo "📦 Building and starting microservices..."
docker-compose up -d --build book-service user-service

echo ""
echo "✅ All services are starting up..."
echo "📚 Book Service will be available at: http://localhost:8081/api/v1"
echo "👥 User Service will be available at: http://localhost:8082/api/v1"
echo ""
echo "🗄️ Database schema auto-generated by Hibernate (Liquibase disabled)"
echo ""
echo "🌐 Infrastructure Services:"
echo "  📊 Kafka UI: http://localhost:8080"
echo "  🗄️  Redis Commander: http://localhost:8090"
echo ""
echo "📋 Swagger Documentation:"
echo "  📚 Book Service: http://localhost:8081/api/v1/swagger-ui.html"
echo "  👥 User Service: http://localhost:8082/api/v1/swagger-ui.html"
echo ""
echo "📊 Health Checks:"
echo "  📚 Book Service: http://localhost:8081/api/v1/actuator/health"
echo "  👥 User Service: http://localhost:8082/api/v1/actuator/health"
echo ""
echo "🐳 To check container status:"
echo "  docker-compose ps"
echo ""
echo "📊 To view logs:"
echo "  docker-compose logs book-service"
echo "  docker-compose logs user-service"
echo ""
echo "🛑 To stop all services:"
echo "  docker-compose down"
